# Generated by Django 6.0 on 2026-01-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_maincategory_subcategory_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': '01. Основная категория', 'verbose_name_plural': '01. Основные категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '03. Товар', 'verbose_name_plural': '03. Товары'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '02. Подкатегория', 'verbose_name_plural': '02. Подкатегории'},
        ),
        migrations.AddField(
            model_name='product',
            name='conductor_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал проводника'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_cores',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ядер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productmeterage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
