# Generated by Django 5.2.6 on 2026-01-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_id_alter_favourite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cable_cross_section',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сечение кабеля, мм²'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='conductor_insulation_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал изоляции проводника'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель/исполнение'),
        ),
        migrations.AddField(
            model_name='product',
            name='outer_insulation_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал внешней изоляции'),
        ),
        migrations.AddField(
            model_name='product',
            name='outer_sheath_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал внешней оболочки'),
        ),
    ]
