# Generated by Django 6.0 on 2026-01-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('organizational_legal_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организационно-правовая форма')),
                ('abbreviated_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сокращенное наименование организации')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование организации')),
                ('inn', models.CharField(blank=True, help_text='10 цифр для юр. лиц, 12 цифр для ИП', max_length=12, null=True, verbose_name='ИНН')),
                ('ogrn_ogrnip', models.CharField(blank=True, help_text='13 цифр для юр. лиц, 15 цифр для ИП', max_length=15, null=True, verbose_name='ОГРН/ОГРНИП')),
                ('kpp', models.CharField(blank=True, help_text='9 цифр', max_length=9, null=True, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, help_text='8 или 10 цифр', max_length=10, null=True, verbose_name='ОКПО')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('legal_index', models.CharField(blank=True, max_length=6, null=True, verbose_name='Индекс (юридический)')),
                ('legal_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион/Область (юридический)')),
                ('legal_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город/Населенный пункт (юридический)')),
                ('legal_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица (юридический)')),
                ('legal_house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом (юридический)')),
                ('legal_building', models.CharField(blank=True, max_length=50, null=True, verbose_name='Корпус/Строение (юридический)')),
                ('legal_office', models.CharField(blank=True, max_length=50, null=True, verbose_name='Офис/Помещение (юридический)')),
                ('matches_legal_address', models.BooleanField(default=False, verbose_name='Совпадает с юридическим адресом')),
                ('actual_index', models.CharField(blank=True, max_length=6, null=True, verbose_name='Индекс (фактический)')),
                ('actual_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион/Область (фактический)')),
                ('actual_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город/Населенный пункт (фактический)')),
                ('actual_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица (фактический)')),
                ('actual_house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом (фактический)')),
                ('actual_building', models.CharField(blank=True, max_length=50, null=True, verbose_name='Корпус/Строение (фактический)')),
                ('actual_office', models.CharField(blank=True, max_length=50, null=True, verbose_name='Офис/Помещение (фактический)')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка')),
                ('bic', models.CharField(blank=True, max_length=50, null=True, verbose_name='БИК')),
                ('settlement_account', models.CharField(blank=True, help_text='20 цифр', max_length=20, null=True, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(blank=True, help_text='20 цифр', max_length=20, null=True, verbose_name='Корреспондентский счет')),
                ('contact_person_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО контактного лица')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('director_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя полностью')),
                ('director_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность руководителя')),
                ('acts_on_basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Действует на основании')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='SupplierUser',
            fields=[
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('tin_certificate', 'Свидетельство ИНН'), ('ogrn_certificate', 'Свидетельство ОГРН/ОГРНИП'), ('charter', 'Устав (для юр. лиц)'), ('director_appointment', 'Документ о назначении руководителя')], max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='companies/documents/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
