# Generated by Django 6.0 on 2026-01-26 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_buyeruser_supplieruser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeruser',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': '01. Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Компания', 'verbose_name_plural': '03. Компании'},
        ),
        migrations.AlterModelOptions(
            name='supplieruser',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': '02. Поставщики'},
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
