# Generated by Django 6.0 on 2026-01-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_buyeruser_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='acts_on_basis',
            field=models.CharField(blank=True, choices=[('Устав', 'Устав'), ('Доверенность', 'Доверенность'), ('Свидетельство о регистрации ИП', 'Свидетельство о регистрации ИП')], max_length=255, null=True, verbose_name='Действует на основании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='organizational_legal_form',
            field=models.CharField(blank=True, choices=[('ООО', 'ООО'), ('ПАО', 'ПАО'), ('АО', 'АО'), ('ИП', 'ИП'), ('ЗАО', 'ЗАО')], max_length=100, null=True, verbose_name='Организационно-правовая форма'),
        ),
    ]
