# Generated by Django 5.2.6 on 2026-01-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_acts_on_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocumentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin_certificate', models.FileField(blank=True, null=True, upload_to='companies/documents/tin/', verbose_name='Свидетельство ИНН')),
                ('ogrn_certificate', models.FileField(blank=True, null=True, upload_to='companies/documents/ogrn/', verbose_name='Свидетельство ОГРН/ОГРНИП')),
                ('charter', models.FileField(blank=True, null=True, upload_to='companies/documents/charter/', verbose_name='Устав (для юр. лиц)')),
                ('director_appointment', models.FileField(blank=True, null=True, upload_to='companies/documents/director/', verbose_name='Документ о назначении руководителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='accounts.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Файлы документов компании',
                'verbose_name_plural': 'Файлы документов компаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
