# Generated by Django 5.2.6 on 2026-01-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_companydocumentfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydocumentfiles',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='charter',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/charter/', verbose_name='Устав (для юр. лиц)'),
        ),
        migrations.AddField(
            model_name='company',
            name='director_appointment',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/director/', verbose_name='Документ о назначении руководителя'),
        ),
        migrations.AddField(
            model_name='company',
            name='ogrn_certificate',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/ogrn/', verbose_name='Свидетельство ОГРН/ОГРНИП'),
        ),
        migrations.AddField(
            model_name='company',
            name='tin_certificate',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/tin/', verbose_name='Свидетельство ИНН'),
        ),
        migrations.DeleteModel(
            name='CompanyDocument',
        ),
        migrations.DeleteModel(
            name='CompanyDocumentFiles',
        ),
    ]
