# Generated by Django 5.2.6 on 2026-01-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_companydocumentfiles_company_company_charter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='charter',
        ),
        migrations.RemoveField(
            model_name='company',
            name='director_appointment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ogrn_certificate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tin_certificate',
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin_certificate', models.FileField(blank=True, null=True, upload_to='companies/documents/tin/', verbose_name='Свидетельство ИНН')),
                ('ogrn_certificate', models.FileField(blank=True, null=True, upload_to='companies/documents/ogrn/', verbose_name='Свидетельство ОГРН/ОГРНИП')),
                ('charter', models.FileField(blank=True, null=True, upload_to='companies/documents/charter/', verbose_name='Устав (для юр. лиц)')),
                ('director_appointment', models.FileField(blank=True, null=True, upload_to='companies/documents/director/', verbose_name='Документ о назначении руководителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
