# Generated by Django 6.0 on 2026-01-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'ordering': ['name'], 'verbose_name': '01. Способ доставки', 'verbose_name_plural': '01. Способы доставки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '03. Заказ', 'verbose_name_plural': '03. Заказы'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': '02. Способ оплаты', 'verbose_name_plural': '02. Способы оплаты'},
        ),
        migrations.AddField(
            model_name='order',
            name='price_for_delivery',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Стоимость доставки'),
            preserve_default=False,
        ),
    ]
