# Generated by Django 6.0 on 2026-01-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_deliverymethod_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '03. Заказ', 'verbose_name_plural': '03. Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Обрабатывается', 'Обрабатывается'), ('Отправлен', 'Отправлен')], default='Ожидание', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
