# Generated by Django 6.0 on 2026-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Обрабатывается', 'Обрабатывается'), ('Отправлен', 'Отправлен')], default='Ожидание', max_length=50, verbose_name='Статус товара в заказе'),
        ),
    ]
