# Generated by Django 6.0 on 2026-01-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('office_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер офиса')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours_weekday', models.CharField(blank=True, help_text='Например: Пн - Пт: 9.00 - 18.00', max_length=100, null=True, verbose_name='Режим работы (будни)')),
                ('working_hours_weekend', models.CharField(blank=True, help_text='Например: Сб - Вс: выходные', max_length=100, null=True, verbose_name='Режим работы (выходные)')),
                ('map_iframe', models.TextField(blank=True, help_text='HTML код для встраивания карты (iframe)', null=True, verbose_name='Карта (iframe)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('file', models.FileField(blank=True, help_text='Документы для подбора кабеля и расчёта стоимости', null=True, upload_to='requests/files/', verbose_name='Прикрепленный файл')),
                ('privacy_policy_agreed', models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
