# Generated by Django 6.0 on 2026-01-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': '01. Контактная информация', 'verbose_name_plural': '01. Контактная информация'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-created_at'], 'verbose_name': '02. Партнер', 'verbose_name_plural': '02. Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': '03. Заявка', 'verbose_name_plural': '03. Заявки'},
        ),
    ]
